name: 'Get and Cache Dependencies'
description: 'Get and cache dependencies using NPM'
inputs:
  caching:
    description: 'Boolean flag to determine whether to cache dependencies or not'
    required: false
    default: 'true'
outputs:
  used-cache:
    description: 'Indicates whether the cache was used or not'
    value: '${{ steps.install.outputs.used-cache }}'
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      id: cache
      if: ${{ inputs.caching == 'true' }}
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: | 
        npm ci
        echo "used-cache=${{ steps.cache.outputs.cache-hit }}" >> "$GITHUB_OUTPUT"
      shell: bash