name: Events Demo
on:
  pull_request:
   types:
    - opened
   branches:
      - main
      - 'dev/*'
      - 'feat/**'
  workflow_dispatch:
  push:
    branches:
      - main
      - 'dev/*'
      - 'feat/**'
    paths-ignore:
      - '.github/workflows/*'
jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: |
          cat <<EOF
          ${{ toJSON(github.event) }}
          EOF